package Vista;
// @author Cristian Gonzalez
import Controlador.ClienteControlador;
import Modelo.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Cristian Gonzalez
 */
public class MantenedorCliente extends javax.swing.JFrame {

    /**
     * Creates new form MantenedorCliente
     */
    public MantenedorCliente() {
        initComponents();
        llenarTablaClientes();
        this.jbtn_salir.requestFocus();
    }

    //Metodo para llenar la tabla con los clientes en vista listar.
    private void llenarTablaClientes() {
        //declaramos variables y controlador
        int rut, telefono;
        String nombre, apellido, dv, email;
        Boolean activo;

        ClienteControlador cc = new ClienteControlador();

        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_clientes_listar.getModel();

        try {
            rut = Integer.parseInt(this.jtxt_buscar_listar.getText());
        } catch (Exception e) {
            rut = 0;
        }

        //nos posicionamos en el inicio de la tabla para llenarla
        modelo.setRowCount(0);

        //llenamos la tabla con los clientes activos
        List<Cliente> lista = cc.buscarTodosClientes();

        for (Cliente cliente : lista) {
            if (cliente.getActivo() == true) {
                rut = cliente.getRut();
                dv = cliente.getDv();
                nombre = cliente.getNombre_cliente();
                apellido = cliente.getApellido();
                telefono = cliente.getTelefono();
                email = cliente.getEmail();

                modelo.addRow(new Object[]{rut, dv, nombre, apellido, telefono, email});
            }
        }

        //Repetimos para llenar la tabla en modificar. Aqui seran incluidos los clientes desactivados(eliminados).   
        cc = new ClienteControlador();

        modelo = (DefaultTableModel) this.jtbl_clientes_modificar.getModel();
        modelo.setRowCount(0);

        //llenamos la tabla con los clientes activos
        lista = cc.buscarTodosClientes();

        for (Cliente cliente : lista) {
            rut = cliente.getRut();
            dv = cliente.getDv();
            nombre = cliente.getNombre_cliente();
            apellido = cliente.getApellido();
                
            modelo.addRow(new Object[]{rut, dv, nombre, apellido});
        }
        
        
        //Y repetimos denuevo para la tabla eliminar.    
        cc = new ClienteControlador();

        modelo = (DefaultTableModel) this.jtbl_clientes_eliminar.getModel();
        modelo.setRowCount(0);

        //llenamos la tabla con los clientes activos
        lista = cc.buscarTodosClientes();

        for (Cliente cliente : lista) {
            if (cliente.getActivo() == true) {
                rut = cliente.getRut();
                dv = cliente.getDv();
                nombre = cliente.getNombre_cliente();
                apellido = cliente.getApellido();
                
                modelo.addRow(new Object[]{rut, dv, nombre, apellido});
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_buscar_listar = new javax.swing.JTextField();
        jbtn_salir_listar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_clientes_listar = new javax.swing.JTable();
        jbtn_buscar_listar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jbtn_salir = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jbtn_añadir = new javax.swing.JButton();
        jtxt_rut_añadir = new javax.swing.JTextField();
        jtxt_dv_añadir = new javax.swing.JTextField();
        jtxt_nombre_añadir = new javax.swing.JTextField();
        jtxt_apellido_añadir = new javax.swing.JTextField();
        jtxt_telefono_añadir = new javax.swing.JTextField();
        jbtn_limpiar = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jtxt_email_añadir = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_buscar_modificar = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_clientes_modificar = new javax.swing.JTable();
        jbtn_buscar_modificar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jbtn_modificar = new javax.swing.JButton();
        jtxt_rut_modificar = new javax.swing.JTextField();
        jtxt_dv_modificar = new javax.swing.JTextField();
        jtxt_nombre_modificar = new javax.swing.JTextField();
        jtxt_apellido_modificar = new javax.swing.JTextField();
        jtxt_email_modificar = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jtxt_telefono_modificar = new javax.swing.JTextField();
        jchk_activo_modificar = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_buscar_eliminar = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbl_clientes_eliminar = new javax.swing.JTable();
        jbtn_buscar_eliminar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0)), "CLIENTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Rut");

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Dv");

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Nombre");

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Apellido");

        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Telefono");

        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Email");

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("Modificar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextField16.setBackground(new java.awt.Color(255, 255, 255));
        jTextField16.setForeground(new java.awt.Color(0, 0, 0));

        jTextField17.setBackground(new java.awt.Color(255, 255, 255));
        jTextField17.setForeground(new java.awt.Color(0, 0, 0));

        jTextField18.setBackground(new java.awt.Color(255, 255, 255));
        jTextField18.setForeground(new java.awt.Color(0, 0, 0));

        jTextField19.setBackground(new java.awt.Color(255, 255, 255));
        jTextField19.setForeground(new java.awt.Color(0, 0, 0));

        jTextField20.setBackground(new java.awt.Color(255, 255, 255));
        jTextField20.setForeground(new java.awt.Color(0, 0, 0));

        jTextField21.setBackground(new java.awt.Color(255, 255, 255));
        jTextField21.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField18)
                            .addComponent(jTextField19)
                            .addComponent(jTextField20)
                            .addComponent(jTextField21))))
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(97, 97, 97))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)))
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(15, 15, 15))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MANTENEDOR CLIENTES");
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese Apellido");

        jtxt_buscar_listar.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_buscar_listar.setForeground(new java.awt.Color(0, 0, 0));
        jtxt_buscar_listar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_buscar_listarFocusGained(evt);
            }
        });
        jtxt_buscar_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_buscar_listarActionPerformed(evt);
            }
        });

        jbtn_salir_listar.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_salir_listar.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_salir_listar.setText("Salir");
        jbtn_salir_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salir_listarActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Copyright - Alison Barraza - Francisco Castillo - Cristian Gonzalez - 2021 ");

        jtbl_clientes_listar.setBackground(new java.awt.Color(255, 255, 255));
        jtbl_clientes_listar.setForeground(new java.awt.Color(0, 0, 0));
        jtbl_clientes_listar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Dv", "Nombre", "Apellido", "Telefono", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_clientes_listar.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtbl_clientes_listar);
        if (jtbl_clientes_listar.getColumnModel().getColumnCount() > 0) {
            jtbl_clientes_listar.getColumnModel().getColumn(0).setResizable(false);
            jtbl_clientes_listar.getColumnModel().getColumn(0).setPreferredWidth(80);
            jtbl_clientes_listar.getColumnModel().getColumn(1).setResizable(false);
            jtbl_clientes_listar.getColumnModel().getColumn(1).setPreferredWidth(30);
            jtbl_clientes_listar.getColumnModel().getColumn(2).setResizable(false);
            jtbl_clientes_listar.getColumnModel().getColumn(2).setPreferredWidth(100);
            jtbl_clientes_listar.getColumnModel().getColumn(3).setResizable(false);
            jtbl_clientes_listar.getColumnModel().getColumn(3).setPreferredWidth(100);
            jtbl_clientes_listar.getColumnModel().getColumn(4).setResizable(false);
            jtbl_clientes_listar.getColumnModel().getColumn(4).setPreferredWidth(80);
            jtbl_clientes_listar.getColumnModel().getColumn(5).setResizable(false);
            jtbl_clientes_listar.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        jbtn_buscar_listar.setText("Buscar");
        jbtn_buscar_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscar_listarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_buscar_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_buscar_listar))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jbtn_salir_listar)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_buscar_listar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscar_listar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_salir_listar)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Listar", jPanel8);

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Copyright - Alison Barraza - Francisco Castillo - Cristian Gonzalez - 2021 ");

        jbtn_salir.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_salir.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_salir.setText("Salir");
        jbtn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salirActionPerformed(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0)), "Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel11.setForeground(new java.awt.Color(0, 0, 0));

        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Rut");

        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("-");

        jLabel41.setForeground(new java.awt.Color(0, 0, 0));
        jLabel41.setText("Nombre");

        jLabel42.setForeground(new java.awt.Color(0, 0, 0));
        jLabel42.setText("Apellido");

        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("Telefono");

        jbtn_añadir.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_añadir.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_añadir.setText("Añadir");
        jbtn_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_añadirActionPerformed(evt);
            }
        });

        jtxt_rut_añadir.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_rut_añadir.setForeground(new java.awt.Color(0, 0, 0));
        jtxt_rut_añadir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_rut_añadirFocusGained(evt);
            }
        });
        jtxt_rut_añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_rut_añadirActionPerformed(evt);
            }
        });

        jtxt_dv_añadir.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_dv_añadir.setForeground(new java.awt.Color(0, 0, 0));
        jtxt_dv_añadir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_dv_añadirFocusGained(evt);
            }
        });

        jtxt_nombre_añadir.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_nombre_añadir.setForeground(new java.awt.Color(0, 0, 0));
        jtxt_nombre_añadir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_nombre_añadirFocusGained(evt);
            }
        });

        jtxt_apellido_añadir.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_apellido_añadir.setForeground(new java.awt.Color(0, 0, 0));
        jtxt_apellido_añadir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_apellido_añadirFocusGained(evt);
            }
        });

        jtxt_telefono_añadir.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_telefono_añadir.setForeground(new java.awt.Color(0, 0, 0));
        jtxt_telefono_añadir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_telefono_añadirFocusGained(evt);
            }
        });

        jbtn_limpiar.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_limpiar.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_limpiar.setText("Limpiar");
        jbtn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarActionPerformed(evt);
            }
        });

        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("Email");

        jtxt_email_añadir.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_email_añadir.setForeground(new java.awt.Color(0, 0, 0));
        jtxt_email_añadir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_email_añadirFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jbtn_limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel42)
                            .addComponent(jLabel41)
                            .addComponent(jLabel39))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_apellido_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel11Layout.createSequentialGroup()
                                    .addComponent(jtxt_rut_añadir)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel40)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtxt_dv_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jtxt_nombre_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_email_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_telefono_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_dv_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_rut_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_nombre_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_apellido_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_telefono_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jtxt_email_añadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_limpiar)
                    .addComponent(jbtn_añadir))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtn_salir)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jbtn_salir)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(38, 38, 38))))
        );

        jTabbedPane1.addTab("Añadir", jPanel7);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese Apellido");

        jtxt_buscar_modificar.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_buscar_modificar.setForeground(new java.awt.Color(0, 0, 0));
        jtxt_buscar_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_buscar_modificarActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Copyright - Alison Barraza - Francisco Castillo - Cristian Gonzalez - 2021 ");

        jtbl_clientes_modificar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Rut", "Dv", "Nombre", "Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_clientes_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbl_clientes_modificarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbl_clientes_modificar);
        if (jtbl_clientes_modificar.getColumnModel().getColumnCount() > 0) {
            jtbl_clientes_modificar.getColumnModel().getColumn(0).setResizable(false);
            jtbl_clientes_modificar.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtbl_clientes_modificar.getColumnModel().getColumn(1).setResizable(false);
            jtbl_clientes_modificar.getColumnModel().getColumn(1).setPreferredWidth(20);
            jtbl_clientes_modificar.getColumnModel().getColumn(2).setResizable(false);
            jtbl_clientes_modificar.getColumnModel().getColumn(2).setPreferredWidth(80);
            jtbl_clientes_modificar.getColumnModel().getColumn(3).setResizable(false);
            jtbl_clientes_modificar.getColumnModel().getColumn(3).setPreferredWidth(80);
        }

        jbtn_buscar_modificar.setText("Buscar");
        jbtn_buscar_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscar_modificarActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0)), "Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(0, 0, 0));

        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Rut");

        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("-");

        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setText("Nombre");

        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setText("Apellido");

        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Email");

        jbtn_modificar.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_modificar.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_modificar.setText("Modificar");
        jbtn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_modificarActionPerformed(evt);
            }
        });

        jtxt_rut_modificar.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_rut_modificar.setForeground(new java.awt.Color(0, 0, 0));
        jtxt_rut_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_rut_modificarActionPerformed(evt);
            }
        });

        jtxt_dv_modificar.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_dv_modificar.setForeground(new java.awt.Color(0, 0, 0));

        jtxt_nombre_modificar.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_nombre_modificar.setForeground(new java.awt.Color(0, 0, 0));

        jtxt_apellido_modificar.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_apellido_modificar.setForeground(new java.awt.Color(0, 0, 0));

        jtxt_email_modificar.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_email_modificar.setForeground(new java.awt.Color(0, 0, 0));

        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setText("Telefono");

        jtxt_telefono_modificar.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_telefono_modificar.setForeground(new java.awt.Color(0, 0, 0));

        jchk_activo_modificar.setText("Activo");
        jchk_activo_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchk_activo_modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jchk_activo_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_rut_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_dv_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_apellido_modificar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_nombre_modificar))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel37)
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_telefono_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxt_email_modificar)))))
                .addGap(16, 16, 16))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jtxt_rut_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jtxt_dv_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jtxt_nombre_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jtxt_apellido_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jtxt_telefono_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_email_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_modificar)
                    .addComponent(jchk_activo_modificar))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(jtxt_buscar_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn_buscar_modificar))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel31)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_buscar_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscar_modificar))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Modificar", jPanel9);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ingrese Apellido");

        jtxt_buscar_eliminar.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_buscar_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        jtxt_buscar_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_buscar_eliminarActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("Salir");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Copyright - Alison Barraza - Francisco Castillo - Cristian Gonzalez - 2021 ");

        jtbl_clientes_eliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rut", "Dv", "Nombre", "Apellido", "Telefono", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_clientes_eliminar.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jtbl_clientes_eliminar);
        if (jtbl_clientes_eliminar.getColumnModel().getColumnCount() > 0) {
            jtbl_clientes_eliminar.getColumnModel().getColumn(0).setResizable(false);
            jtbl_clientes_eliminar.getColumnModel().getColumn(0).setPreferredWidth(80);
            jtbl_clientes_eliminar.getColumnModel().getColumn(1).setResizable(false);
            jtbl_clientes_eliminar.getColumnModel().getColumn(1).setPreferredWidth(30);
            jtbl_clientes_eliminar.getColumnModel().getColumn(2).setResizable(false);
            jtbl_clientes_eliminar.getColumnModel().getColumn(2).setPreferredWidth(100);
            jtbl_clientes_eliminar.getColumnModel().getColumn(3).setResizable(false);
            jtbl_clientes_eliminar.getColumnModel().getColumn(3).setPreferredWidth(100);
            jtbl_clientes_eliminar.getColumnModel().getColumn(4).setResizable(false);
            jtbl_clientes_eliminar.getColumnModel().getColumn(4).setPreferredWidth(80);
            jtbl_clientes_eliminar.getColumnModel().getColumn(5).setResizable(false);
            jtbl_clientes_eliminar.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        jbtn_buscar_eliminar.setText("Buscar");
        jbtn_buscar_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscar_eliminarActionPerformed(evt);
            }
        });

        jbtn_eliminar.setBackground(new java.awt.Color(204, 204, 204));
        jbtn_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxt_buscar_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jbtn_buscar_eliminar))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jButton10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel32))))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 115, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_buscar_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jbtn_buscar_eliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtn_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jLabel32))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Eliminar", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salirActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_salirActionPerformed

    private void jtxt_buscar_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_buscar_listarActionPerformed
        this.jtxt_buscar_listar.setText("");
    }//GEN-LAST:event_jtxt_buscar_listarActionPerformed

    private void jbtn_salir_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salir_listarActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_salir_listarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jtxt_buscar_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_buscar_eliminarActionPerformed
        this.jtxt_buscar_eliminar.setText("");
    }//GEN-LAST:event_jtxt_buscar_eliminarActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarActionPerformed
        
        //Actualizamos el atributo "activo" a false para "eliminar" al cliente seleccionado.
        Cliente cliente;
        int fila, rut;
        
        ClienteControlador cc = new ClienteControlador();
        
        try{
            fila = this.jtbl_clientes_modificar.getSelectedRow();
            rut = (int) this.jtbl_clientes_modificar.getValueAt(fila,0);

            cliente = cc.buscarClienteRut(rut);
            
            cliente.setActivo(false);
            
            cc.actualizarCliente(cliente);
            
            
        }catch(Exception e){
            System.out.println("e.getMessage");
        }
        
        
    }//GEN-LAST:event_jbtn_eliminarActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jbtn_buscar_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscar_eliminarActionPerformed
                                                      
        //iniciamos variables, controladores y la tabla
        int rut, telefono;
        String nombre, apellido, dv, email;
        Boolean activo;

        ClienteControlador cc = new ClienteControlador();

        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_clientes_eliminar.getModel();

        apellido = this.jtxt_buscar_eliminar.getText();
        modelo.setRowCount(0);

        //revisamos criterio de busqueda y se llena la tabla con los resultados
        if (apellido.equals("")) {

            List<Cliente> lista = cc.buscarTodosClientes();

            for (Cliente cliente : lista) {
                if (cliente.getActivo()) {
                    rut = cliente.getRut();
                    dv = cliente.getDv();
                    nombre = cliente.getNombre_cliente();
                    apellido = cliente.getApellido();
                    telefono = cliente.getTelefono();
                    email = cliente.getEmail();

                    modelo.addRow(new Object[]{rut, dv, nombre, apellido, telefono, email});
                }
            }
        } else {

            List<Cliente> lista = cc.buscarClienteApellido(apellido);

            for (Cliente cliente : lista) {
                if (cliente.getActivo()) {
                    rut = cliente.getRut();
                    dv = cliente.getDv();
                    nombre = cliente.getNombre_cliente();
                    apellido = cliente.getApellido();
                    telefono = cliente.getTelefono();
                    email = cliente.getEmail();

                    modelo.addRow(new Object[]{rut, dv, nombre, apellido, telefono, email});
                }
            }
        }    
    }//GEN-LAST:event_jbtn_buscar_eliminarActionPerformed

    private void jbtn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_modificarActionPerformed
        //rescatamos los datos
        String rut_str = this.jtxt_rut_modificar.getText();
        String dv = this.jtxt_dv_modificar.getText();
        String nombre = this.jtxt_nombre_modificar.getText();
        String apellido = this.jtxt_apellido_modificar.getText();
        String telefono_str = this.jtxt_telefono_modificar.getText();
        String email = this.jtxt_email_modificar.getText();
        Boolean activo = this.jchk_activo_modificar.isSelected();

        //vemos que no hayan datos sin llenar
        if (rut_str.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese rut", "Validacion", 2);
            this.jtxt_rut_añadir.requestFocus();
            return;
        }
        if (dv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese dv", "Validacion", 2);
            this.jtxt_dv_añadir.requestFocus();
            return;
        }
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese nombre", "Validacion", 2);
            this.jtxt_nombre_añadir.requestFocus();
            return;
        }
        if (apellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese apellido", "Validacion", 2);
            this.jtxt_apellido_añadir.requestFocus();
            return;
        }
        if (telefono_str.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese telefono", "Validacion", 2);
            this.jtxt_telefono_añadir.requestFocus();
            return;
        }
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese email", "Validacion", 2);
            this.jtxt_email_añadir.requestFocus();
            return;
        }
        int rut, telefono;
        rut = Integer.parseInt(rut_str);
        telefono = Integer.parseInt(telefono_str);
        

        //Validaciones extra.

        
        
        
        
        //Guardamos los nuevos datos del cliente.
        Cliente cliente = new Cliente(rut, dv, nombre, apellido, telefono, email, activo);

        ClienteControlador cc = new ClienteControlador();
               
        if (cc.actualizarCliente(cliente)) {
            JOptionPane.showMessageDialog(this, "Cliente modificado!", "Ingreso", 1);
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no se pudo modificar", "Validacion", 1);
        }
    }//GEN-LAST:event_jbtn_modificarActionPerformed

    private void jtxt_rut_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_rut_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_rut_modificarActionPerformed

    private void jbtn_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_añadirActionPerformed
        //rescatamos los datos
        String rut_str = this.jtxt_rut_añadir.getText();
        String dv = this.jtxt_dv_añadir.getText();
        String nombre = this.jtxt_nombre_añadir.getText();
        String apellido = this.jtxt_apellido_añadir.getText();
        String telefono_str = this.jtxt_telefono_añadir.getText();
        String email = this.jtxt_email_añadir.getText();
        Boolean activo = true;

        //vemos que no hayan datos sin llenar
        if (rut_str.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese rut", "Validacion", 2);
            this.jtxt_rut_añadir.requestFocus();
            return;
        }
        if (dv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese dv", "Validacion", 2);
            this.jtxt_dv_añadir.requestFocus();
            return;
        }
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese nombre", "Validacion", 2);
            this.jtxt_nombre_añadir.requestFocus();
            return;
        }
        if (apellido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese apellido", "Validacion", 2);
            this.jtxt_apellido_añadir.requestFocus();
            return;
        }
        if (telefono_str.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese telefono", "Validacion", 2);
            this.jtxt_telefono_añadir.requestFocus();
            return;
        }
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese email", "Validacion", 2);
            this.jtxt_email_añadir.requestFocus();
            return;
        }
        int rut, telefono;
        rut = Integer.parseInt(rut_str);
        telefono = Integer.parseInt(telefono_str);
        

        //Validaciones extra
        
        
        
        //Guardamos los datos del nuevo cliente.
        Cliente cliente = new Cliente(rut, dv, nombre, apellido, telefono, email, activo);

        ClienteControlador cc = new ClienteControlador();

        if (cc.agregarCliente(cliente)) {
            JOptionPane.showMessageDialog(this, "Cliente ingresado!", "Ingreso", 1);
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no se pudo ingresar", "Validacion", 1);
        }


    }//GEN-LAST:event_jbtn_añadirActionPerformed

    private void jtxt_rut_añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_rut_añadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_rut_añadirActionPerformed

    private void jbtn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarActionPerformed

        this.jtxt_rut_añadir.setText("");
        this.jtxt_dv_añadir.setText("");
        this.jtxt_nombre_añadir.setText("");
        this.jtxt_apellido_añadir.setText("");
        this.jtxt_telefono_añadir.setText("");
        this.jtxt_email_añadir.setText("");

        this.jtxt_rut_añadir.requestFocus();

    }//GEN-LAST:event_jbtn_limpiarActionPerformed

    private void jtxt_rut_añadirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_rut_añadirFocusGained

        this.jtxt_rut_añadir.setText("");

    }//GEN-LAST:event_jtxt_rut_añadirFocusGained

    private void jtxt_dv_añadirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_dv_añadirFocusGained
        this.jtxt_dv_añadir.setText("");
    }//GEN-LAST:event_jtxt_dv_añadirFocusGained

    private void jtxt_nombre_añadirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_nombre_añadirFocusGained
        this.jtxt_nombre_añadir.setText("");
    }//GEN-LAST:event_jtxt_nombre_añadirFocusGained

    private void jtxt_apellido_añadirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_apellido_añadirFocusGained
        this.jtxt_apellido_añadir.setText("");
    }//GEN-LAST:event_jtxt_apellido_añadirFocusGained

    private void jtxt_email_añadirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_email_añadirFocusGained
        this.jtxt_email_añadir.setText("");
    }//GEN-LAST:event_jtxt_email_añadirFocusGained

    private void jtxt_telefono_añadirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_telefono_añadirFocusGained
        this.jtxt_telefono_añadir.setText("");
    }//GEN-LAST:event_jtxt_telefono_añadirFocusGained

    private void jbtn_buscar_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscar_listarActionPerformed
        //iniciamos variables, controladores y la tabla
        int rut, telefono;
        String nombre, apellido, dv, email;
        
        ClienteControlador cc = new ClienteControlador();

        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_clientes_listar.getModel();

        apellido = this.jtxt_buscar_listar.getText();
        modelo.setRowCount(0);

        //revisamos criterio de busqueda y se llena la tabla con los resultados
        if (apellido.equals("")) {

            List<Cliente> lista = cc.buscarTodosClientes();

            for (Cliente cliente : lista) {
                if (cliente.getActivo()) {
                    rut = cliente.getRut();
                    dv = cliente.getDv();
                    nombre = cliente.getNombre_cliente();
                    apellido = cliente.getApellido();
                    telefono = cliente.getTelefono();
                    email = cliente.getEmail();

                    modelo.addRow(new Object[]{rut, dv, nombre, apellido, telefono, email});
                }
            }
        } else {

            List<Cliente> lista = cc.buscarClienteApellido(apellido);

            for (Cliente cliente : lista) {
                if (cliente.getActivo()) {
                    rut = cliente.getRut();
                    dv = cliente.getDv();
                    nombre = cliente.getNombre_cliente();
                    apellido = cliente.getApellido();
                    telefono = cliente.getTelefono();
                    email = cliente.getEmail();

                    modelo.addRow(new Object[]{rut, dv, nombre, apellido, telefono, email});
                }
            }
        }

    }//GEN-LAST:event_jbtn_buscar_listarActionPerformed

    private void jtxt_buscar_listarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_buscar_listarFocusGained
        this.jtxt_buscar_listar.setText("");
    }//GEN-LAST:event_jtxt_buscar_listarFocusGained

    private void jtxt_buscar_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_buscar_modificarActionPerformed
        this.jtxt_buscar_modificar.setText("");
    }//GEN-LAST:event_jtxt_buscar_modificarActionPerformed

    private void jtbl_clientes_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbl_clientes_modificarMouseClicked
        Cliente cliente;
        int fila, rut;
        
        ClienteControlador cc = new ClienteControlador();
        
        try{
            fila = this.jtbl_clientes_modificar.getSelectedRow();
            rut = (int) this.jtbl_clientes_modificar.getValueAt(fila,0);

            cliente = cc.buscarClienteRut(rut);
            
            this.jtxt_rut_modificar.setText(String.valueOf(cliente.rut));
            this.jtxt_dv_modificar.setText(cliente.dv);
            this.jtxt_nombre_modificar.setText(cliente.nombre_cliente);
            this.jtxt_apellido_modificar.setText(cliente.apellido);
            this.jtxt_telefono_modificar.setText(String.valueOf(cliente.telefono));
            this.jtxt_email_modificar.setText(cliente.email);
            this.jchk_activo_modificar.setSelected(cliente.activo);
            
        }catch(Exception e){
            System.out.println("e.getMessage");
        }    
    }//GEN-LAST:event_jtbl_clientes_modificarMouseClicked

    private void jbtn_buscar_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscar_modificarActionPerformed
        //iniciamos variables, controladores y la tabla
        int rut, telefono;
        String nombre, apellido, dv, email;
        Boolean activo;

        ClienteControlador cc = new ClienteControlador();

        DefaultTableModel modelo = (DefaultTableModel) this.jtbl_clientes_modificar.getModel();

        apellido = this.jtxt_buscar_modificar.getText();
        modelo.setRowCount(0);

        //revisamos criterio de busqueda y se llena la tabla con los resultados
        if (apellido.equals("")) {

            List<Cliente> lista = cc.buscarTodosClientes();

            for (Cliente cliente : lista) {
                if (cliente.getActivo()) {
                    rut = cliente.getRut();
                    dv = cliente.getDv();
                    nombre = cliente.getNombre_cliente();
                    apellido = cliente.getApellido();
                    telefono = cliente.getTelefono();
                    email = cliente.getEmail();

                    modelo.addRow(new Object[]{rut, dv, nombre, apellido, telefono, email});
                }
            }
        } else {

            List<Cliente> lista = cc.buscarClienteApellido(apellido);

            for (Cliente cliente : lista) {
                if (cliente.getActivo()) {
                    rut = cliente.getRut();
                    dv = cliente.getDv();
                    nombre = cliente.getNombre_cliente();
                    apellido = cliente.getApellido();
                    telefono = cliente.getTelefono();
                    email = cliente.getEmail();

                    modelo.addRow(new Object[]{rut, dv, nombre, apellido, telefono, email});
                }
            }
        }
    }//GEN-LAST:event_jbtn_buscar_modificarActionPerformed

    private void jchk_activo_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchk_activo_modificarActionPerformed
        
    }//GEN-LAST:event_jchk_activo_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JButton jbtn_añadir;
    private javax.swing.JButton jbtn_buscar_eliminar;
    private javax.swing.JButton jbtn_buscar_listar;
    private javax.swing.JButton jbtn_buscar_modificar;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_limpiar;
    private javax.swing.JButton jbtn_modificar;
    private javax.swing.JButton jbtn_salir;
    private javax.swing.JButton jbtn_salir_listar;
    private javax.swing.JCheckBox jchk_activo_modificar;
    private javax.swing.JTable jtbl_clientes_eliminar;
    private javax.swing.JTable jtbl_clientes_listar;
    private javax.swing.JTable jtbl_clientes_modificar;
    private javax.swing.JTextField jtxt_apellido_añadir;
    private javax.swing.JTextField jtxt_apellido_modificar;
    private javax.swing.JTextField jtxt_buscar_eliminar;
    private javax.swing.JTextField jtxt_buscar_listar;
    private javax.swing.JTextField jtxt_buscar_modificar;
    private javax.swing.JTextField jtxt_dv_añadir;
    private javax.swing.JTextField jtxt_dv_modificar;
    private javax.swing.JTextField jtxt_email_añadir;
    private javax.swing.JTextField jtxt_email_modificar;
    private javax.swing.JTextField jtxt_nombre_añadir;
    private javax.swing.JTextField jtxt_nombre_modificar;
    private javax.swing.JTextField jtxt_rut_añadir;
    private javax.swing.JTextField jtxt_rut_modificar;
    private javax.swing.JTextField jtxt_telefono_añadir;
    private javax.swing.JTextField jtxt_telefono_modificar;
    // End of variables declaration//GEN-END:variables
}
