/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author abarr
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
        //inicializa la ventana en el centrol
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuAd = new javax.swing.JMenu();
        jmiVenta = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiHisVenta = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jmiMantCli = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jmiMantProduc = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmi_cerrarCesion = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmi_salir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiAyuda = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Administración");

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Copyright - Alison Barraza - Francisco Castillo - Cristian Gonzalez - 2021");

        jMenuAd.setBackground(new java.awt.Color(0, 153, 153));
        jMenuAd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuAd.setText("Menú");
        jMenuAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAdActionPerformed(evt);
            }
        });

        jmiVenta.setText("Nueva Venta");
        jmiVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVentaActionPerformed(evt);
            }
        });
        jMenuAd.add(jmiVenta);
        jMenuAd.add(jSeparator1);

        jmiHisVenta.setText("Historial Ventas");
        jmiHisVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiHisVentaActionPerformed(evt);
            }
        });
        jMenuAd.add(jmiHisVenta);
        jMenuAd.add(jSeparator2);

        jmiMantCli.setText("Mantenedor Cliente");
        jmiMantCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMantCliActionPerformed(evt);
            }
        });
        jMenuAd.add(jmiMantCli);
        jMenuAd.add(jSeparator3);

        jmiMantProduc.setText("Mantenedor Productos");
        jmiMantProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMantProducActionPerformed(evt);
            }
        });
        jMenuAd.add(jmiMantProduc);
        jMenuAd.add(jSeparator4);

        jmi_cerrarCesion.setText("Cerrar Sesión");
        jmi_cerrarCesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cerrarCesionActionPerformed(evt);
            }
        });
        jMenuAd.add(jmi_cerrarCesion);
        jMenuAd.add(jSeparator5);

        jmi_salir.setText("Salir");
        jmi_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_salirActionPerformed(evt);
            }
        });
        jMenuAd.add(jmi_salir);

        jMenuBar2.add(jMenuAd);

        jMenu4.setBackground(new java.awt.Color(0, 153, 153));
        jMenu4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setText("Ayuda");

        jmiAyuda.setText("Ayuda con...");
        jMenu4.add(jmiAyuda);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 277, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVentaActionPerformed
        
        GenerarVenta genVenta= new GenerarVenta();
        genVenta.setVisible(true);
    }//GEN-LAST:event_jmiVentaActionPerformed

    private void jmiMantProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMantProducActionPerformed
        
        MantenedorProducto manProductos =new MantenedorProducto();
        manProductos.setVisible(true);
    }//GEN-LAST:event_jmiMantProducActionPerformed

    private void jMenuAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAdActionPerformed
        
    }//GEN-LAST:event_jMenuAdActionPerformed

    private void jmiHisVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiHisVentaActionPerformed
        ListarVentas listVentas= new ListarVentas ();
        listVentas.setVisible(true);
    }//GEN-LAST:event_jmiHisVentaActionPerformed

    private void jmiMantCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMantCliActionPerformed
        MantenedorCliente manCliente =new MantenedorCliente();
        manCliente.setVisible(true);
    }//GEN-LAST:event_jmiMantCliActionPerformed

    private void jmi_cerrarCesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cerrarCesionActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jmi_cerrarCesionActionPerformed

    private void jmi_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmi_salirActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuAdmin().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuAd;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem jmiAyuda;
    private javax.swing.JMenuItem jmiHisVenta;
    private javax.swing.JMenuItem jmiMantCli;
    private javax.swing.JMenuItem jmiMantProduc;
    private javax.swing.JMenuItem jmiVenta;
    private javax.swing.JMenuItem jmi_cerrarCesion;
    private javax.swing.JMenuItem jmi_salir;
    // End of variables declaration//GEN-END:variables
}
